language: cpp
os: linux
version: ~> 1.0

branches:
  only:
  - staging
  - trying
  - master
  # release branch
  - /^release\/[\d\.]+$/
  # release tag
  - /^v[\d\.]+$/

stages:
- name: process snaps
  if: (type = pull_request
        AND head_repo = MirServer/mir)
      OR (type != pull_request
        AND repo = MirServer/mir)
- name: test
  # don't test on pushes to master or release pull requests or tag events
  # TODO: enable release pull request testing when we have more CI power
  if: NOT (( branch = master AND type = push )
             OR ( head_branch =~ ^release/[\d\.]+$ ))
      AND tag IS blank
- name: sanitize
  if: type = cron
      AND repo = MirServer/mir
      AND branch = master
- name: upload to ppa:mir-team
  if: type = push
      AND repo = MirServer/mir
      AND ( branch = master
            OR branch =~ ^release/[\d\.]+$
            OR tag =~ ^v[\d\.]+$ )

env:
  global:
    # SPREAD_GOOGLE_KEY
  - secure: C+R+J6LFdpge/aRDiCSVmU+Ps4sA0BhibQZgHi2iy20QkuD3NFiKcU7mISiEfWzsrRyLxtxYadWrfXXovyaSKDkIzuArVi/l5PyYRlLh7DYM/chk0CEbcoBpRKllgH57wU8ki7mCvksIbMdjZZo8iFIL79JUMaMvCK/QOwjqvj7d0I0qsJRT228G3n1KXKgRRL/9cafnjnzjHorrPpVJAkg8T7/QLO7uh7D5L5+KcHcf2Ws2/V05lhFXApCxL2QPLTCjn7cONKCaRfg35MkeFxWwTNm+JhGEW70A8Uk3qFWObWMPDEGrLkS5RF1Gw4zXrlqOyZRtK6VCaqsnJPVhqhLXliq9jNd/dbr/6L7hSa/t8ewbkXFuOqJzq240bEn4OCUFJOl9mwhklj14/Y+/xV3wRxIF6qdCDB99nirJKtwPjeYsKdCHLwKN/kj6yHhAU9JBDm+D5Odo9ny33eFPfQ+6SyGHL6BZKg7sVi8wbZwiTjmoN3wFZwSVto/4w1JiUHhJkMkEeIOlsQyfzJZl1DOTQDl4UiEAa8lhjvfqz8TqdXdu/3UPC9tokjnm45Joa5WkcnnvVsBoro+mSar6DipC6nb/+5yuguIEzcGha8iNyNMpMY0Ei0V+PwCl+M5k/vFtdA+HbSGs6VI4JvRd9awQ7geohn5ram5l4as67Sg=
  - DEBFULLNAME="Mir CI Bot"
  - DEBEMAIL="mir-ci-bot@canonical.com"
  - SPREAD_PATH=/tmp/spread
  jobs:
  - TASK=google:ubuntu-20.04-64:spread/build/sbuild:debian_sid
  - TASK=google:ubuntu-20.04-64:spread/build/sbuild:ubuntu_devel
  - TASK=google:ubuntu-20.04-64:spread/build/sbuild:ubuntu_bionic
  - TASK=google:ubuntu-20.04-64:spread/build/sbuild:ubuntu
  - TASK=google:ubuntu-20.04-64:spread/build/sbuild:ubuntu_proposed
  - TASK=google:ubuntu-20.04-64:spread/build/sbuild:ubuntu_arm64
  - TASK=google:ubuntu-20.04-64:spread/build/ubuntu:rpi
  - TASK=google:ubuntu-20.04-64:spread/build/ubuntu:clang
  - TASK=google:fedora-31-64:spread/build/fedora:amd64
  - TASK=google:fedora-32-64:spread/build/fedora:amd64
  - TASK=google:fedora-rawhide-64:spread/build/fedora:amd64

before_install:
- mkdir -p ${SPREAD_PATH}
- pushd "${SPREAD_PATH}"
- curl -s -O https://niemeyer.s3.amazonaws.com/spread-amd64.tar.gz
- tar xzvf spread-amd64.tar.gz
- popd

script:
- ${SPREAD_PATH}/spread -v ${TASK}

jobs:
  include:
  - &ppa-upload
    stage: upload to ppa:mir-team
    env: RELEASE=18.04
    git:
      depth: false
    before_install: &decrypt-bot-data
    - openssl aes-256-cbc -K $encrypted_0102c5bea602_key -iv $encrypted_0102c5bea602_iv
      -in tools/bot-data.tar.xz.enc -out tools/bot-data.tar.xz -d
    - tar --extract --xz --file tools/bot-data.tar.xz --directory ${HOME}
    script:
    - tools/ppa-upload.sh
    addons:
      apt:
        packages:
        - debhelper
        - devscripts
        - dput
        - fakeroot
        - python-bzrlib
        - python-launchpadlib
        - python-paramiko
  - <<: *ppa-upload
    env: RELEASE=20.04
  - <<: *ppa-upload
    env: RELEASE=devel

  - &sanitize
    stage: sanitize
    env: TASK=google:ubuntu-20.04-64:spread/build/ubuntu:asan
  - <<: *sanitize
    env: TASK=google:ubuntu-20.04-64:spread/build/ubuntu:tsan
  - <<: *sanitize
    env: TASK=google:ubuntu-20.04-64:spread/build/ubuntu:ubsan
  - <<: *sanitize
    env: TASK=google:ubuntu-20.04-64:spread/build/ubuntu:asan_clang
  - <<: *sanitize
    env: TASK=google:ubuntu-20.04-64:spread/build/ubuntu:tsan_clang
  - <<: *sanitize
    env: TASK=google:ubuntu-20.04-64:spread/build/ubuntu:ubsan_clang

  - stage: process snaps
    env: ~
    language: python
    python: 3.6
    dist: xenial
    before_install: *decrypt-bot-data
    install:
    - pip install -r tools/requirements.txt
    - if [ ${TRAVIS_EVENT_TYPE} == cron ]; then sudo apt update; sudo apt install snapd; sudo snap install snapd review-tools; fi
    script:
    - tools/process_snaps.py
  allow_failures:
    - env: TASK=google:ubuntu-devel-proposed-64:spread/build/ubuntu:amd64
    - env: TASK=google:fedora-rawhide-64:spread/build/fedora:amd64
  fast_finish: true
